### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "scandit-datacapture-frameworks-core":

### ISSUE THREAD

**Issue by zed-em1** [Scandit/scandit-react-native-datacapture-core#15]
In Podfile:
    scandit-react-native-datacapture-core (from `../node_modules/scandit-react-native-datacapture-core`) was resolved to 6.20.1, which depends on
      scandit-datacapture-frameworks-core (= 6.20.1)

None of your spec sources contain a spec satisfying the dependency: `scandit-datacapture-frameworks-core (= 6.20.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

I'm using react-native 0.72.6

**Comment by ScanditSupport** [comment]
Hi @zed-em1 

Thank you for reporting that. We're already aware of this issue and we're currently working on its resolution. 

If you want us to inform you about the progress, please get in contact with us directly via: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by ScanditSupport** [comment]
Hi @wmaca-friday ,

The issue should be fixed now, could you please try running `pod install --repo-update`?

**Comment by wmaca-friday** [comment]
It works now, but there is a new problem. Your modules are not exporting anything and I get this error:

```
Cannot read property 'DataCaptureContext' of undefined
```

It is being imported correctly:

```import {
	Barcode,
	BarcodeCapture,
	BarcodeCaptureListener,
	BarcodeCaptureSettings,
	default as BarcodeCaptureDefaults,
	Symbology
} from "scandit-react-native-datacapture-barcode```

**Comment by ScanditSupport** [comment]
Hi @wmaca-friday,

Please note that the DataCaptureContext should be imported from scandit-react-native-datacapture-core, not barcode:
https://github.com/Scandit/datacapture-react-native-samples/blob/master/BarcodeCaptureSimpleSample/app/App.tsx#L3-L22

If the issue persists, could you please reach out to us directly and share your scanning components?
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by wmaca-friday** [comment]
I just pasted incorrectly, but I am importing from the correct package.
It still does not work if I use a more recente version.

And if I use an older one, I have issues controlling the torch on iOS.

**Comment by wmaca-friday** [comment]
Upon further inspection, it seems this error is being caused by another error:

`Invariant Violation: Tried to register two views with the same name RNTDataCaptureView, js engine: hermes `

**Comment by ScanditSupport** [comment]
Hi @wmaca-friday,

As we can see - you have already reached out to us via support@scandit.com, so we will continue the conversation there.
